{
 "title": "sfvisdev",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime - sfvisdev",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "rawSql": "SELECT uptime FROM sfOrinMonitoring.sfvisdev ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Board Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT hostname, model, ip_address FROM sfOrinMonitoring.sfvisdev ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT p_number, id, cudnn, module, serial_number, tensorrt, vulkan FROM sfOrinMonitoring.sfvisdev ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT GPU FROM sfOrinMonitoring.sfvisdev ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT CPU1, CPU2, CPU3, CPU4, CPU5, CPU6 FROM sfOrinMonitoring.sfvisdev ORDER BY time DESC LIMIT 1; "
    }
   ]
  },
  {
   "title": "Fan",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT `Fan pwmfan0` FROM sfOrinMonitoring.sfvisdev LIMIT 50;"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT RAM, SWAP FROM sfOrinMonitoring.sfvisdev LIMIT 50;"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT disk_available_gb FROM sfOrinMonitoring.sfvisdev ORDER BY time DESC LIMIT 50  "
    }
   ]
  },
  {
   "title": "Board Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT `Temp CPU`, `Temp GPU`, `Temp SOC0`, `Temp SOC1`, `Temp SOC2`, `Temp tj` FROM sfOrinMonitoring.sfvisdev ORDER BY time DESC LIMIT 1; "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 17 },
   "content": "<div style=\\\"text-align: center;\\\">\r\n<img src=\"http://sfgrafana.sf.local/Full_Transparent_Background.png\" alt=\"Grafana Image\" style=\"width:100%; height:auto;\">  \r\n"
  }
 ]
}